UPDATE "PageSectionTranslation" AS translation
SET title = localized.title,
    body = localized.body
FROM "PageSection" AS section,
     "Page" AS page,
     (VALUES
       ('en'::"ContentLocale", 'About Us', 'Yueshou Bio is a national-level specialized, refined, distinctive, and innovative "Little Giant" enterprise focused on peptide research, development, production, and application. The company hosts a national postdoctoral research station and an academician-expert workstation, as well as a provincial enterprise research institute. It is also Guangdong Province''s first Peptide Synthesis Engineering Research Center and has been granted 108 related invention patents, making it one of the leading enterprises in large-scale peptide production in China. The company has established a "one core, two wings, dual-wheel drive" development strategy, with drug peptides and their technical services as the core, and cosmetic peptides and other peptides as the two supporting wings. This strategy drives growth through both pharmaceutical and non-pharmaceutical peptides, while simultaneously advancing innovation capabilities and expanding market channels and customer base.'),
       ('zh-CN'::"ContentLocale", '关于我们', '粤首生物是一家专注于多肽研发、生产和应用的国家级专精特新“小巨人”企业。公司设有国家级博士后科研工作站、院士专家工作站以及省级企业研究院，同时也是广东省首家多肽合成工程研究中心，已获得108项相关发明专利，是国内多肽规模化生产领域的领先企业之一。公司确立了“一核两翼、双轮驱动”的发展战略，以药物多肽及其技术服务为核心，以化妆品多肽和其他多肽为两翼，通过医药与非医药多肽双轮驱动发展，同时提升创新能力，拓展市场渠道与客户群体。'),
       ('de'::"ContentLocale", 'Über uns', 'Yueshou Bio ist ein auf nationaler Ebene anerkanntes, spezialisiertes und innovatives „Little Giant“-Unternehmen mit Schwerpunkt auf Forschung, Entwicklung, Produktion und Anwendung von Peptiden. Das Unternehmen verfügt über eine nationale Postdoktoranden-Forschungsstation, eine Akademiker- und Expertenstation sowie ein Forschungsinstitut auf Provinzebene. Darüber hinaus ist es das erste Forschungszentrum für Peptidsynthese-Engineering in der Provinz Guangdong und besitzt 108 einschlägige Erfindungspatente, womit es zu den führenden Unternehmen für die großtechnische Peptidproduktion in China zählt. Yueshou verfolgt die Entwicklungsstrategie „ein Kern, zwei Flügel, dualer Antrieb“: Arzneimittelpeptide und die zugehörigen technischen Dienstleistungen bilden den Kern, kosmetische Peptide und andere Peptide die beiden unterstützenden Flügel. Das Wachstum wird sowohl durch pharmazeutische als auch durch nicht pharmazeutische Peptide vorangetrieben, während zugleich die Innovationsfähigkeit gestärkt und Marktkanäle sowie Kundenbasis erweitert werden.'),
       ('fr'::"ContentLocale", 'À propos de nous', 'Yueshou Bio est une entreprise nationale spécialisée et innovante de type « Little Giant », axée sur la recherche, le développement, la production et l’application des peptides. L’entreprise dispose d’une station nationale de recherche postdoctorale, d’une station d’académiciens et d’experts, ainsi que d’un institut de recherche d’entreprise de niveau provincial. Elle est également le premier centre de recherche en ingénierie de la synthèse peptidique de la province du Guangdong et détient 108 brevets d’invention dans ce domaine, ce qui en fait l’une des entreprises chinoises de référence pour la production de peptides à grande échelle. Yueshou a adopté une stratégie de développement « un cœur, deux ailes, double moteur » : les peptides pharmaceutiques et les services techniques associés constituent le cœur, tandis que les peptides cosmétiques et les autres peptides forment les deux ailes. Cette stratégie stimule la croissance grâce aux peptides pharmaceutiques et non pharmaceutiques, tout en renforçant les capacités d’innovation et en élargissant les canaux commerciaux et la clientèle.'),
       ('es'::"ContentLocale", 'Sobre nosotros', 'Yueshou Bio es una empresa nacional especializada e innovadora del tipo «Little Giant», centrada en la investigación, el desarrollo, la producción y la aplicación de péptidos. La empresa cuenta con una estación nacional de investigación posdoctoral, una estación de académicos y expertos y un instituto empresarial de investigación de ámbito provincial. También es el primer Centro de Investigación en Ingeniería de Síntesis de Péptidos de la provincia de Guangdong y posee 108 patentes de invención relacionadas, lo que la convierte en una de las empresas líderes de China en la producción de péptidos a gran escala. Yueshou ha establecido una estrategia de desarrollo de «un núcleo, dos alas y doble motor»: los péptidos farmacéuticos y sus servicios técnicos constituyen el núcleo, mientras que los péptidos cosméticos y otros péptidos forman las dos alas de apoyo. Esta estrategia impulsa el crecimiento mediante péptidos farmacéuticos y no farmacéuticos, al tiempo que fortalece la capacidad de innovación y amplía los canales de mercado y la base de clientes.')
     ) AS localized(locale, title, body)
WHERE page.slug = 'home'
  AND section."pageId" = page.id
  AND section.type = 'ABOUT'
  AND section."deletedAt" IS NULL
  AND translation."pageSectionId" = section.id
  AND translation.locale = localized.locale;
