import { Button, Card, Input, List, Space, Typography } from "antd";
import Link from "next/link";
import { InquiryStatusForm } from "@/components/admin/domain-forms";
import { requireUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db/prisma";
import { inquiryFilterSchema, inquiryWhere } from "@/features/inquiries/filters";
import { changeInquiryStatusAction, saveInquiryNotesAction } from "./actions";

export default async function InquiriesPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: "NEW" | "IN_PROGRESS" | "RESOLVED" | "ARCHIVED"; start?: string; end?: string; page?: string }> }) { await requireUser(); const query = await searchParams; const page = Math.min(1000, Math.max(1, Number(query.page ?? 1) || 1)); const parsed = inquiryFilterSchema.safeParse({ q: query.q || undefined, status: query.status || undefined, start: query.start || undefined, end: query.end || undefined }); const filters = parsed.success ? parsed.data : {}; const inquiries = await prisma.inquiry.findMany({ where: inquiryWhere(filters), include: { attachments: true }, orderBy: { createdAt: "desc" }, skip: (page - 1) * 50, take: 50 }); const params = new URLSearchParams(); if (filters.q) params.set("q", filters.q); if (filters.status) params.set("status", filters.status); if (filters.start) params.set("start", filters.start); if (filters.end) params.set("end", filters.end); const pageHref = (number: number) => { const copy = new URLSearchParams(params); copy.set("page", String(number)); return `/admin/inquiries?${copy}`; }; const exportHref = `/api/admin/inquiries/export?${params}`; return <main><Typography.Title level={1}>Inquiries</Typography.Title><Space><Button href={exportHref} target="_blank">Export CSV</Button></Space><Card><form><Space><Input name="q" defaultValue={filters.q} placeholder="Search company, contact or email" aria-label="Search inquiries" /><select name="status" defaultValue={filters.status ?? ""} aria-label="Inquiry status"><option value="">All statuses</option>{["NEW", "IN_PROGRESS", "RESOLVED", "ARCHIVED"].map((value) => <option key={value} value={value}>{value}</option>)}</select><Input type="date" name="start" defaultValue={filters.start} aria-label="Start date" /><Input type="date" name="end" defaultValue={filters.end} aria-label="End date" /><Button htmlType="submit">Filter</Button></Space></form><p>Page {page}</p><Space>{page > 1 ? <Link href={pageHref(page - 1)}>Previous</Link> : null}{inquiries.length === 50 ? <Link href={pageHref(page + 1)}>Next</Link> : null}</Space><List dataSource={inquiries} locale={{ emptyText: "No inquiries yet." }} renderItem={(item) => <List.Item><Card style={{ width: "100%" }} title={`${item.companyName} — ${item.contactName}`}><p><a href={`mailto:${item.email}`}>{item.email}</a>{item.country ? ` · ${item.country}` : ""}</p><p>{item.message}</p>{item.attachments.length ? <p>Private attachments: {item.attachments.map((attachment) => <Link key={attachment.id} href={`/api/admin/inquiries/attachments/${attachment.id}/download`}>{attachment.filename} </Link>)}</p> : null}<InquiryStatusForm inquiryId={item.id} status={item.status} notes={item.internalNotes} update={changeInquiryStatusAction} saveNotes={saveInquiryNotesAction} /></Card></List.Item>} /></Card></main>; }
