"use server";

import { revalidatePath } from "next/cache";
import { prismaNewsAdminRepository } from "@/features/admin/domain-repository";
import { createNewsAdminService } from "@/features/admin/news";
import { invalidatePublishedEntity } from "@/features/publishing/cache";
import { requireUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db/prisma";
import { SUPPORTED_LOCALES } from "@/lib/i18n/config";
import { z } from "zod";

const data = (input: unknown) => input instanceof FormData ? JSON.parse(String(input.get("payload") ?? "{}")) as object : input as object;
const service = () => createNewsAdminService({ repository: prismaNewsAdminRepository, invalidate: (type, slug) => invalidatePublishedEntity(type, slug, SUPPORTED_LOCALES) });
export async function saveArticleAction(input: unknown) { const actor = await requireUser(); const payload = data(input) as { id?: string }; const before = payload.id ? await prisma.article.findUnique({ where: { id: payload.id }, select: { slug: true, status: true } }) : null; const result = await service().save({ ...(payload as object), actor }); const after = await prisma.article.findUniqueOrThrow({ where: { id: result.id }, select: { slug: true, status: true } }); if (before?.status === "PUBLISHED") invalidatePublishedEntity("article", before.slug, SUPPORTED_LOCALES); if (after.status === "PUBLISHED") invalidatePublishedEntity("article", after.slug, SUPPORTED_LOCALES); revalidatePath("/admin/news"); return result; }
export async function archiveArticleCategoryAction(input: unknown) { const actor = await requireUser(); const payload = data(input) as { categoryId: string }; await service().archiveCategory({ categoryId: payload.categoryId, actor }); revalidatePath("/admin/news"); }
export async function archiveTagAction(input: unknown) { const actor = await requireUser(); const payload = data(input) as { tagId: string }; await service().archiveTag({ tagId: payload.tagId, actor }); revalidatePath("/admin/news"); }
export async function saveArticleCategoryAction(input: unknown) { const actor = await requireUser(); const payload = z.object({ id: z.string().optional(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), title: z.string().trim().min(1).max(160), body: z.string().trim().max(4_000).default("") }).parse(data(input)); await prisma.$transaction(async (tx) => { const category = payload.id ? await tx.articleCategory.update({ where: { id: payload.id }, data: { slug: payload.slug } }) : await tx.articleCategory.create({ data: { slug: payload.slug } }); await tx.articleCategoryTranslation.upsert({ where: { articleCategoryId_locale: { articleCategoryId: category.id, locale: "en" } }, update: { title: payload.title, body: payload.body }, create: { articleCategoryId: category.id, locale: "en", title: payload.title, body: payload.body } }); await tx.auditLog.create({ data: { actorId: actor.id, action: "ARTICLE_CATEGORY_SAVED", entityType: "ArticleCategory", entityId: category.id } }); }); revalidatePath("/admin/news"); }
export async function saveTagAction(input: unknown) { const actor = await requireUser(); const payload = z.object({ id: z.string().optional(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), name: z.string().trim().min(1).max(160) }).parse(data(input)); await prisma.$transaction(async (tx) => { const tag = payload.id ? await tx.tag.update({ where: { id: payload.id }, data: { slug: payload.slug, name: payload.name } }) : await tx.tag.create({ data: { slug: payload.slug, name: payload.name } }); await tx.auditLog.create({ data: { actorId: actor.id, action: "TAG_SAVED", entityType: "Tag", entityId: tag.id } }); }); revalidatePath("/admin/news"); }
