"use server";

import { revalidatePath } from "next/cache";
import { prismaNewsAdminRepository, serializableRetry } from "@/features/admin/domain-repository";
import { createNewsAdminService } from "@/features/admin/news";
import { invalidatePublishedEntity } from "@/features/publishing/cache";
import { requireRole, requireUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db/prisma";
import { SUPPORTED_LOCALES } from "@/lib/i18n/config";
import { z } from "zod";

const data = (input: unknown) => input instanceof FormData ? JSON.parse(String(input.get("payload") ?? "{}")) as object : input as object;
const service = () => createNewsAdminService({ repository: prismaNewsAdminRepository, invalidate: (type, slug) => invalidatePublishedEntity(type, slug, SUPPORTED_LOCALES) });
export async function saveArticleAction(input: unknown) { const actor = await requireUser(); const payload = data(input) as { id?: string }; const before = payload.id ? await prisma.article.findUnique({ where: { id: payload.id }, select: { slug: true, status: true } }) : null; const result = await service().save({ ...(payload as object), actor }); const after = await prisma.article.findUniqueOrThrow({ where: { id: result.id }, select: { slug: true, status: true } }); if (before?.status === "PUBLISHED") invalidatePublishedEntity("article", before.slug, SUPPORTED_LOCALES); if (after.status === "PUBLISHED") invalidatePublishedEntity("article", after.slug, SUPPORTED_LOCALES); revalidatePath("/admin/news"); return result; }
const categoryPayload = z.object({ id: z.string().min(1).optional(), version: z.string().datetime().optional(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), title: z.string().trim().min(1).max(160), body: z.string().trim().max(4_000), status: z.enum(["DRAFT", "PUBLISHED"]).default("DRAFT") }).superRefine((value, context) => { if (value.id && !value.version) context.addIssue({ code: "custom", message: "version is required when editing a category" }); if (!value.id && value.version) context.addIssue({ code: "custom", message: "version is only valid when editing a category" }); });
const tagPayload = z.object({ id: z.string().min(1).optional(), version: z.string().datetime().optional(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), name: z.string().trim().min(1).max(160).optional(), title: z.string().trim().min(1).max(160).optional() }).refine((value) => Boolean(value.name ?? value.title), "Name is required").superRefine((value, context) => { if (value.id && !value.version) context.addIssue({ code: "custom", message: "version is required when editing a tag" }); if (!value.id && value.version) context.addIssue({ code: "custom", message: "version is only valid when editing a tag" }); }).transform((value) => ({ ...value, name: value.name ?? value.title! }));
export async function archiveArticleCategoryAction(input: unknown) { const actor = await requireUser(); const payload = z.object({ categoryId: z.string().min(1), version: z.string().datetime() }).parse(data(input)); await service().archiveCategory({ categoryId: payload.categoryId, version: payload.version, actor }); revalidatePath("/admin/news"); }
export async function archiveTagAction(input: unknown) { const actor = await requireUser(); const payload = z.object({ tagId: z.string().min(1), version: z.string().datetime() }).parse(data(input)); await service().archiveTag({ tagId: payload.tagId, version: payload.version, actor }); revalidatePath("/admin/news"); }
export async function saveArticleCategoryAction(input: unknown) { const actor = await requireRole("ADMIN"); const payload = categoryPayload.parse(data(input)); await serializableRetry(() => prisma.$transaction(async (tx) => { const previous = payload.id ? await tx.articleCategory.findFirst({ where: { id: payload.id, updatedAt: new Date(payload.version!), deletedAt: null } }) : null; if (payload.id && !previous) throw new Error("Category changed by another administrator; reload and try again"); const category = previous ? await tx.articleCategory.update({ where: { id: previous.id }, data: { slug: payload.slug, status: payload.status, publishedAt: payload.status === "PUBLISHED" ? previous.publishedAt ?? new Date() : previous.publishedAt } }) : await tx.articleCategory.create({ data: { slug: payload.slug, status: payload.status, publishedAt: payload.status === "PUBLISHED" ? new Date() : null } }); await tx.articleCategoryTranslation.upsert({ where: { articleCategoryId_locale: { articleCategoryId: category.id, locale: "en" } }, update: { title: payload.title, body: payload.body }, create: { articleCategoryId: category.id, locale: "en", title: payload.title, body: payload.body } }); await tx.auditLog.create({ data: { actorId: actor.id, action: "ARTICLE_CATEGORY_SAVED", entityType: "ArticleCategory", entityId: category.id, metadata: { status: payload.status } } }); }, { isolationLevel: "Serializable" })); revalidatePath("/admin/news"); }
export async function saveTagAction(input: unknown) { const actor = await requireRole("ADMIN"); const payload = tagPayload.parse(data(input)); await serializableRetry(() => prisma.$transaction(async (tx) => { const previous = payload.id ? await tx.tag.findFirst({ where: { id: payload.id, updatedAt: new Date(payload.version!), deletedAt: null } }) : null; if (payload.id && !previous) throw new Error("Tag changed by another administrator; reload and try again"); const tag = previous ? await tx.tag.update({ where: { id: previous.id }, data: { slug: payload.slug, name: payload.name } }) : await tx.tag.create({ data: { slug: payload.slug, name: payload.name } }); await tx.auditLog.create({ data: { actorId: actor.id, action: "TAG_SAVED", entityType: "Tag", entityId: tag.id } }); }, { isolationLevel: "Serializable" })); revalidatePath("/admin/news"); }
