-- Preserve the complete Chinese About content under zh-CN before replacing the
-- incorrectly Chinese English translation.
UPDATE "PageTranslation" AS zh
SET body = en.body,
    title = '关于粤首',
    "seoTitle" = '关于粤首'
FROM "Page" AS page,
     "PageTranslation" AS en
WHERE page.slug = 'about'
  AND en."pageId" = page.id
  AND en.locale = 'en'
  AND zh."pageId" = page.id
  AND zh.locale = 'zh-CN';

UPDATE "PageTranslation" AS translation
SET body = localized.body,
    title = localized.title,
    "seoTitle" = localized.title,
    "seoDescription" = localized.description
FROM "Page" AS page,
     (VALUES
       ('en'::"ContentLocale", 'About Yueshou',
        '<p>Founded in 2015, Yueshou Co., Ltd. specializes in the research, development, manufacturing, and sale of peptide products and related services. Recognized as a national-level specialized and innovative “Little Giant” enterprise, the company has advanced, efficient capabilities in peptide synthesis, purification, and large-scale production, as well as a Guangdong Postdoctoral Workstation and an Academician and Expert Workstation. Guided by its commitment to human health and beauty, Yueshou draws on industry-leading peptide synthesis and modification technologies to supply peptide-based cosmetic ingredients and pharmaceutical products and to provide related services.</p>
<p>Through years of technical development and process exploration, the company has established an industry-leading platform for peptide drug synthesis and manufacturing. Its proprietary core technologies for the large-scale production of peptide active pharmaceutical ingredients include functional resin modification, special amino acid fragment synthesis, segmented synthesis of long peptides, directed synthesis of polycyclic peptides, control of long-peptide aggregates, and modification of specific peptide functional groups. Process development and manufacturing capabilities for peptide APIs form the foundation of the company’s competitive strength and business growth. Yueshou selects peptide API candidates with strong market potential and competitiveness in China and internationally, and has built a broad pipeline that includes well-known products such as leuprolide, semaglutide, liraglutide, and linaclotide.</p>
<p>Since its establishment, the company has provided peptide CDMO/CRO services to prominent innovative pharmaceutical companies, including China Resources Double-Crane and Simcere Pharmaceutical. Its peptide APIs and advanced pharmaceutical intermediates are exported to the United States, Russia, Pakistan, South Korea, and other countries and regions.</p>
<p>According to Frost &amp; Sullivan, the company held the largest share of China’s peptide cosmetic ingredient market in 2021. Yueshou continues to innovate in peptide ingredient technologies and further strengthens its cost advantages through process improvements, enabling it to offer highly competitive customized products. Drawing on years of industry experience and extensive technical expertise, the company provides end-to-end services covering early product development, research, experimentation, powder production, stock-solution formulation, stability testing, and efficacy evaluation for peptide cosmetic ingredients. This enables Yueshou to participate from the earliest stages of a customer’s product design, tailor peptide ingredients to the intended positioning and application of the final product, and refine solutions throughout product design and commercialization in response to customer needs.</p>
<p>The company remains committed to independent innovation, continuously advancing research projects in peptide cosmetic ingredients. It has also established strategic collaborations with leading cosmetics companies such as Proya, Bloomage Biotech, and Marubi, applying its scientific expertise and proven experience in peptide ingredient applications to support the continued development of peptides in cosmetics.</p>
<h2>Contact Information</h2>
<p><strong>Address:</strong> Room 332, 3rd Floor, No. 55 Guangcong 3rd Road, Taihe Town, Baiyun District, Guangzhou, China<br><strong>Telephone:</strong> <a href="tel:057583835818">0575-83835818</a><br><strong>Website:</strong> <a href="https://www.yueshou-peptide.com" target="_blank" rel="noopener noreferrer">www.yueshou-peptide.com</a></p>',
        'Learn about Yueshou’s peptide research, manufacturing capabilities, CDMO/CRO services, and cosmetic ingredient expertise.'),
       ('de'::"ContentLocale", 'Über Yueshou',
        '<p>Die 2015 gegründete Yueshou Co., Ltd. ist auf Forschung, Entwicklung, Herstellung und Vertrieb von Peptidprodukten sowie damit verbundene Dienstleistungen spezialisiert. Als staatlich anerkanntes, spezialisiertes und innovatives „Little Giant“-Unternehmen verfügt Yueshou über fortschrittliche und effiziente Kapazitäten für Peptidsynthese, Reinigung und Produktion im großen Maßstab sowie über eine Postdoktorandenstation der Provinz Guangdong und eine Akademiker- und Expertenstation. Mit dem Ziel, Gesundheit und Schönheit der Menschen zu fördern, nutzt das Unternehmen seine branchenführenden Kerntechnologien für Peptidsynthese und -modifikation, um kosmetische Peptidwirkstoffe und pharmazeutische Peptidprodukte zu liefern und entsprechende Dienstleistungen anzubieten.</p>
<p>Durch langjährige technische Entwicklung und Prozessforschung hat das Unternehmen eine branchenführende Plattform für die Synthese und Herstellung von Peptidarzneimitteln aufgebaut. Zu den eigenen Kerntechnologien für die großtechnische Produktion peptidischer Wirkstoffe zählen die Modifikation funktioneller Harze, die Synthese spezieller Aminosäurefragmente, die segmentierte Synthese langer Peptide, die gezielte Synthese polyzyklischer Peptide, die Kontrolle von Aggregaten langer Peptide und die Modifikation spezifischer funktioneller Gruppen. Die Prozessentwicklung und Produktionskompetenz für Peptidwirkstoffe bilden die Grundlage der Wettbewerbsfähigkeit und Geschäftsentwicklung. Yueshou entwickelt Wirkstoffkandidaten mit großem Marktpotenzial und hoher Wettbewerbsfähigkeit in China und auf internationalen Märkten und hat eine umfangreiche Pipeline aufgebaut, darunter bekannte Produkte wie Leuprorelin, Semaglutid, Liraglutid und Linaclotid.</p>
<p>Seit seiner Gründung erbringt das Unternehmen Peptid-CDMO/CRO-Dienstleistungen für namhafte innovative Pharmaunternehmen, darunter China Resources Double-Crane und Simcere Pharmaceutical. Peptidwirkstoffe und fortgeschrittene pharmazeutische Zwischenprodukte werden unter anderem in die USA, nach Russland, Pakistan und Südkorea exportiert.</p>
<p>Laut Frost &amp; Sullivan hatte das Unternehmen 2021 den größten Marktanteil bei kosmetischen Peptidwirkstoffen in China. Yueshou entwickelt seine Technologien für Peptidwirkstoffe kontinuierlich weiter und stärkt durch Prozessverbesserungen seine Kostenvorteile, um maßgeschneiderte Produkte mit klaren Wettbewerbsvorteilen anzubieten. Dank langjähriger Branchenerfahrung und umfassender technischer Kompetenz deckt das Unternehmen die gesamte Wertschöpfungskette ab: frühe Produktentwicklung, Forschung, Versuche, Pulverproduktion, Formulierung von Stammlösungen, Stabilitätsprüfung und Wirksamkeitsbewertung. So kann Yueshou bereits in der frühen Produktkonzeption mitwirken, Peptidwirkstoffe an Positionierung und Anwendung des Endprodukts anpassen und Lösungen während Produktgestaltung und Vermarktung entsprechend den Kundenanforderungen weiterentwickeln.</p>
<p>Das Unternehmen setzt konsequent auf eigenständige Innovation und treibt Forschungsprojekte im Bereich kosmetischer Peptidwirkstoffe voran. Darüber hinaus bestehen strategische Kooperationen mit führenden Kosmetikunternehmen wie Proya, Bloomage Biotech und Marubi. Mit wissenschaftlicher Kompetenz und erfolgreicher Anwendungserfahrung unterstützt Yueshou die weitere Entwicklung von Peptiden in Kosmetikprodukten.</p>
<h2>Kontaktinformationen</h2>
<p><strong>Adresse:</strong> Raum 332, 3. Etage, Guangcong 3rd Road 55, Taihe, Bezirk Baiyun, Guangzhou, China<br><strong>Telefon:</strong> <a href="tel:057583835818">0575-83835818</a><br><strong>Website:</strong> <a href="https://www.yueshou-peptide.com" target="_blank" rel="noopener noreferrer">www.yueshou-peptide.com</a></p>',
        'Erfahren Sie mehr über Yueshous Peptidforschung, Produktion, CDMO/CRO-Dienstleistungen und Kompetenz bei kosmetischen Wirkstoffen.'),
       ('fr'::"ContentLocale", 'À propos de Yueshou',
        '<p>Fondée en 2015, Yueshou Co., Ltd. se consacre à la recherche, au développement, à la fabrication et à la commercialisation de produits peptidiques, ainsi qu’aux services associés. Reconnue au niveau national comme entreprise spécialisée et innovante « Little Giant », elle dispose de capacités avancées et efficaces de synthèse, de purification et de production de peptides à grande échelle, ainsi que d’une station postdoctorale de la province du Guangdong et d’une station d’académiciens et d’experts. Animée par sa volonté de contribuer à la santé et à la beauté, Yueshou s’appuie sur des technologies de pointe en synthèse et en modification des peptides pour fournir des ingrédients peptidiques cosmétiques, des produits pharmaceutiques peptidiques et les services correspondants.</p>
<p>Au fil de nombreuses années de développement technique et d’exploration des procédés, l’entreprise a mis en place une plateforme de référence pour la synthèse et la fabrication de médicaments peptidiques. Ses technologies propriétaires destinées à la production à grande échelle de principes actifs peptidiques comprennent la modification de résines fonctionnelles, la synthèse de fragments d’acides aminés spéciaux, la synthèse segmentée de peptides longs, la synthèse dirigée de peptides polycycliques, la maîtrise des agrégats de peptides longs et la modification de groupes fonctionnels spécifiques. Les capacités de développement des procédés et de fabrication des API peptidiques constituent le socle de sa compétitivité et de sa croissance. Yueshou sélectionne des candidats présentant un fort potentiel de marché et une solide compétitivité en Chine comme à l’international, et a constitué un vaste portefeuille comprenant notamment le leuproréline, le sémaglutide, le liraglutide et le linaclotide.</p>
<p>Depuis sa création, l’entreprise fournit des services CDMO/CRO dans le domaine des peptides à des sociétés pharmaceutiques innovantes de premier plan, notamment China Resources Double-Crane et Simcere Pharmaceutical. Ses API peptidiques et intermédiaires pharmaceutiques avancés sont exportés vers les États-Unis, la Russie, le Pakistan, la Corée du Sud et d’autres pays et régions.</p>
<p>Selon Frost &amp; Sullivan, l’entreprise détenait en 2021 la plus grande part du marché chinois des ingrédients peptidiques cosmétiques. Yueshou poursuit l’innovation technologique dans ce domaine et renforce ses avantages de coûts grâce à l’amélioration continue des procédés, afin de proposer des produits personnalisés particulièrement compétitifs. Forte de nombreuses années d’expérience et d’une expertise technique approfondie, l’entreprise offre des services couvrant toute la chaîne de valeur : développement initial, recherche, expérimentation, production de poudres, formulation de solutions mères, essais de stabilité et évaluation de l’efficacité. Elle peut ainsi intervenir dès les premières étapes de conception, adapter les ingrédients peptidiques au positionnement et à l’usage du produit final, puis faire évoluer les solutions au cours de la conception et de la commercialisation selon les besoins du client.</p>
<p>L’entreprise reste attachée à l’innovation indépendante et poursuit activement ses projets de recherche sur les ingrédients peptidiques cosmétiques. Elle a également noué des partenariats stratégiques avec de grands groupes cosmétiques tels que Proya, Bloomage Biotech et Marubi. Son expertise scientifique et son expérience reconnue des applications peptidiques contribuent au développement continu des peptides dans les cosmétiques.</p>
<h2>Coordonnées</h2>
<p><strong>Adresse :</strong> Bureau 332, 3e étage, 55 Guangcong 3rd Road, Taihe, district de Baiyun, Guangzhou, Chine<br><strong>Téléphone :</strong> <a href="tel:057583835818">0575-83835818</a><br><strong>Site web :</strong> <a href="https://www.yueshou-peptide.com" target="_blank" rel="noopener noreferrer">www.yueshou-peptide.com</a></p>',
        'Découvrez la recherche, la production, les services CDMO/CRO et l’expertise de Yueshou dans les ingrédients peptidiques cosmétiques.'),
       ('es'::"ContentLocale", 'Acerca de Yueshou',
        '<p>Fundada en 2015, Yueshou Co., Ltd. se dedica a la investigación, el desarrollo, la fabricación y la venta de productos peptídicos, así como a los servicios relacionados. Reconocida a nivel nacional como empresa especializada e innovadora «Little Giant», cuenta con capacidades avanzadas y eficientes de síntesis, purificación y producción de péptidos a gran escala, además de una estación posdoctoral de la provincia de Guangdong y una estación de académicos y expertos. Con el propósito de contribuir a la salud y la belleza, Yueshou aprovecha sus tecnologías líderes de síntesis y modificación de péptidos para suministrar ingredientes peptídicos cosméticos, productos farmacéuticos peptídicos y los servicios correspondientes.</p>
<p>Tras años de desarrollo técnico y exploración de procesos, la empresa ha establecido una plataforma líder para la síntesis y fabricación de fármacos peptídicos. Sus tecnologías propias para la producción a gran escala de principios activos peptídicos incluyen la modificación de resinas funcionales, la síntesis de fragmentos especiales de aminoácidos, la síntesis segmentada de péptidos largos, la síntesis dirigida de péptidos policíclicos, el control de agregados de péptidos largos y la modificación de grupos funcionales específicos. Las capacidades de desarrollo de procesos y fabricación de API peptídicos constituyen la base de su competitividad y crecimiento. Yueshou selecciona candidatos con gran potencial de mercado y sólida competitividad tanto en China como a escala internacional, y ha desarrollado una amplia cartera que incluye productos conocidos como leuprorelina, semaglutida, liraglutida y linaclotida.</p>
<p>Desde su fundación, la empresa presta servicios CDMO/CRO de péptidos a destacadas compañías farmacéuticas innovadoras, entre ellas China Resources Double-Crane y Simcere Pharmaceutical. Sus API peptídicos e intermediarios farmacéuticos avanzados se exportan a Estados Unidos, Rusia, Pakistán, Corea del Sur y otros países y regiones.</p>
<p>Según Frost &amp; Sullivan, en 2021 la empresa tenía la mayor cuota del mercado chino de ingredientes peptídicos cosméticos. Yueshou continúa innovando en tecnologías de ingredientes peptídicos y refuerza sus ventajas de costes mediante mejoras de procesos para ofrecer productos personalizados altamente competitivos. Gracias a años de experiencia sectorial y a una amplia capacidad técnica, la empresa presta servicios integrales que abarcan el desarrollo inicial, la investigación, la experimentación, la producción de polvo, la formulación de soluciones madre, las pruebas de estabilidad y la evaluación de eficacia. Esto permite a Yueshou intervenir desde las primeras fases del diseño, adaptar los ingredientes peptídicos al posicionamiento y uso del producto final y perfeccionar las soluciones durante el diseño y la comercialización según las necesidades del cliente.</p>
<p>La empresa mantiene su compromiso con la innovación independiente y sigue impulsando proyectos de investigación en ingredientes peptídicos cosméticos. También ha establecido colaboraciones estratégicas con empresas cosméticas líderes como Proya, Bloomage Biotech y Marubi. Su experiencia científica y su trayectoria en aplicaciones de ingredientes peptídicos contribuyen al desarrollo continuo de los péptidos en el sector cosmético.</p>
<h2>Información de contacto</h2>
<p><strong>Dirección:</strong> Sala 332, 3.ª planta, n.º 55 de Guangcong 3rd Road, Taihe, distrito de Baiyun, Guangzhou, China<br><strong>Teléfono:</strong> <a href="tel:057583835818">0575-83835818</a><br><strong>Sitio web:</strong> <a href="https://www.yueshou-peptide.com" target="_blank" rel="noopener noreferrer">www.yueshou-peptide.com</a></p>',
        'Conozca la investigación, fabricación, servicios CDMO/CRO y experiencia de Yueshou en ingredientes peptídicos cosméticos.')
     ) AS localized(locale, title, body, description)
WHERE page.slug = 'about'
  AND translation."pageId" = page.id
  AND translation.locale = localized.locale;

UPDATE "NavigationItemTranslation" AS translation
SET title = localized.title
FROM "NavigationItem" AS item,
     (VALUES
       ('home', 'en'::"ContentLocale", 'Home'), ('home', 'zh-CN'::"ContentLocale", '首页'), ('home', 'de'::"ContentLocale", 'Startseite'), ('home', 'fr'::"ContentLocale", 'Accueil'), ('home', 'es'::"ContentLocale", 'Inicio'),
       ('about', 'en'::"ContentLocale", 'About'), ('about', 'zh-CN'::"ContentLocale", '关于我们'), ('about', 'de'::"ContentLocale", 'Über uns'), ('about', 'fr'::"ContentLocale", 'À propos'), ('about', 'es'::"ContentLocale", 'Acerca de'),
       ('services', 'en'::"ContentLocale", 'Services'), ('services', 'zh-CN'::"ContentLocale", '服务'), ('services', 'de'::"ContentLocale", 'Leistungen'), ('services', 'fr'::"ContentLocale", 'Services'), ('services', 'es'::"ContentLocale", 'Servicios'),
       ('products', 'en'::"ContentLocale", 'Products'), ('products', 'zh-CN'::"ContentLocale", '产品'), ('products', 'de'::"ContentLocale", 'Produkte'), ('products', 'fr'::"ContentLocale", 'Produits'), ('products', 'es'::"ContentLocale", 'Productos'),
       ('quality', 'en'::"ContentLocale", 'Quality'), ('quality', 'zh-CN'::"ContentLocale", '质量'), ('quality', 'de'::"ContentLocale", 'Qualität'), ('quality', 'fr'::"ContentLocale", 'Qualité'), ('quality', 'es'::"ContentLocale", 'Calidad'),
       ('news', 'en'::"ContentLocale", 'News'), ('news', 'zh-CN'::"ContentLocale", '新闻'), ('news', 'de'::"ContentLocale", 'Neuigkeiten'), ('news', 'fr'::"ContentLocale", 'Actualités'), ('news', 'es'::"ContentLocale", 'Noticias'),
       ('contact', 'en'::"ContentLocale", 'Contact'), ('contact', 'zh-CN'::"ContentLocale", '联系我们'), ('contact', 'de'::"ContentLocale", 'Kontakt'), ('contact', 'fr'::"ContentLocale", 'Contact'), ('contact', 'es'::"ContentLocale", 'Contacto')
     ) AS localized(slug, locale, title)
WHERE translation."navigationItemId" = item.id
  AND item.slug = localized.slug
  AND translation.locale = localized.locale;
