import { z } from "zod";
import { EditorAuthorizationError, EditorValidationError, type AdminEditorActor } from "./editors";

const statuses = ["NEW", "IN_PROGRESS", "RESOLVED", "ARCHIVED"] as const;
type InquiryStatus = (typeof statuses)[number];
export type InquiryAdminRepository = { getStatus(inquiryId: string): Promise<InquiryStatus | null>; updateStatus(input: { inquiryId: string; expectedStatus: InquiryStatus; status: InquiryStatus; actorId: string }): Promise<boolean>; saveNotes?(input: { inquiryId: string; internalNotes: string | null; actorId: string }): Promise<boolean> };
const allowedTransitions: Record<InquiryStatus, readonly InquiryStatus[]> = { NEW: ["IN_PROGRESS", "ARCHIVED"], IN_PROGRESS: ["RESOLVED", "ARCHIVED"], RESOLVED: ["ARCHIVED"], ARCHIVED: [] };
function requireActor(actor: AdminEditorActor | null): asserts actor is AdminEditorActor { if (!actor) throw new EditorAuthorizationError("Authentication required"); }
export function createInquiryAdminService(dependencies: { repository: InquiryAdminRepository }) { return { async changeStatus(input: { actor: AdminEditorActor | null; inquiryId: string; status: InquiryStatus }) { requireActor(input.actor); const data = z.object({ inquiryId: z.string().min(1), status: z.enum(statuses) }).parse(input); const current = await dependencies.repository.getStatus(data.inquiryId); if (!current) throw new EditorValidationError("Inquiry not found"); if (!allowedTransitions[current].includes(data.status)) throw new EditorValidationError("Invalid inquiry status transition"); if (!await dependencies.repository.updateStatus({ ...data, expectedStatus: current, actorId: input.actor.id })) throw new EditorValidationError("Inquiry changed by another administrator; reload and try again"); }, async saveNotes(input: { actor: AdminEditorActor | null; inquiryId: string; internalNotes: string | null }) { requireActor(input.actor); const data = z.object({ inquiryId: z.string().min(1), internalNotes: z.string().trim().max(10_000).nullable() }).parse(input); if (!dependencies.repository.saveNotes || !await dependencies.repository.saveNotes({ ...data, actorId: input.actor.id })) throw new EditorValidationError("Inquiry changed by another administrator; reload and try again"); } }; }
