"use client";

import { Button, Card, Form, Input, Select, Space, Switch, Tabs } from "antd";
import { useState, useTransition } from "react";

import { SUPPORTED_LOCALES, type Locale } from "@/lib/i18n/config";

type Mutation = (input: unknown) => Promise<void>;
type Translation = { locale: Locale; title: string; body: string; alt?: string };

function TranslationFields({ media = false }: { media?: boolean }) {
  return <Tabs items={SUPPORTED_LOCALES.map((locale) => ({ key: locale, label: locale === "en" ? "English (required)" : locale, children: <Space direction="vertical" style={{ width: "100%" }}><Form.Item name={["translations", locale, "title"]} label="Title" rules={[{ required: locale === "en" }]}><Input /></Form.Item><Form.Item name={["translations", locale, "body"]} label="Body" rules={[{ required: locale === "en" && !media }]}><Input.TextArea rows={4} /></Form.Item>{media ? <Form.Item name={["translations", locale, "alt"]} label="Alternative text" rules={[{ required: locale === "en" }]}><Input /></Form.Item> : null}</Space> }))} />;
}

function toTranslations(value: Record<string, { title?: string; body?: string; alt?: string }>) {
  return SUPPORTED_LOCALES.flatMap((locale) => {
    const translation = value[locale];
    return translation?.title ? [{ locale, title: translation.title, body: translation.body ?? "", ...(translation.alt === undefined ? {} : { alt: translation.alt }) }] : [];
  });
}

export function SiteSettingsForm({ initial, save }: { initial: { key: string; version: string | null; value: Record<string, unknown>; translations: Translation[]; status: string }; save: Mutation }) {
  const [form] = Form.useForm(); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string>();
  const translations = Object.fromEntries(initial.translations.map((item) => [item.locale, item]));
  return <Form form={form} layout="vertical" initialValues={{ value: initial.value, translations }} onFinish={(values) => startTransition(async () => { try { setError(undefined); await save({ key: initial.key, version: initial.version, status: initial.status, value: values.value ?? {}, translations: toTranslations(values.translations ?? {}) }); } catch { setError("Could not save settings. Please reload and try again."); } })}>
    {error ? <p role="alert">{error}</p> : null}<Form.Item name={["value", "companyName"]} label="Company name"><Input /></Form.Item><Form.Item name={["value", "slogan"]} label="Slogan"><Input /></Form.Item><Form.Item name={["value", "email"]} label="Email"><Input type="email" /></Form.Item><Form.Item name={["value", "phone"]} label="Phone"><Input /></Form.Item><Form.List name={["value", "addressLines"]}>{(fields, { add, remove }) => <Card size="small" title="Company address">{fields.map((field) => <Space key={field.key}><Form.Item {...field}><Input aria-label="Address line" /></Form.Item><Button onClick={() => remove(field.name)}>Remove</Button></Space>)}<Button onClick={() => add()}>Add address line</Button></Card>}</Form.List><Form.Item name={["value", "logoMediaId"]} label="Logo media ID"><Input /></Form.Item><Form.Item name={["value", "faviconMediaId"]} label="Favicon media ID"><Input /></Form.Item><Form.List name={["value", "socialLinks"]}>{(fields, { add, remove }) => <Card size="small" title="Social links">{fields.map((field) => <Space key={field.key}><Form.Item {...field} name={[field.name, "label"]}><Input aria-label="Social label" /></Form.Item><Form.Item {...field} name={[field.name, "href"]}><Input aria-label="Social HTTPS link" /></Form.Item><Button onClick={() => remove(field.name)}>Remove</Button></Space>)}<Button onClick={() => add()}>Add social link</Button></Card>}</Form.List><Card size="small" title="Default SEO"><Form.Item name={["value", "defaultSeo", "title"]} label="SEO title"><Input /></Form.Item><Form.Item name={["value", "defaultSeo", "description"]} label="SEO description"><Input.TextArea /></Form.Item></Card><Form.List name={["value", "footerColumns"]}>{(fields, { add, remove }) => <Card size="small" title="Footer columns">{fields.map((field) => <Space key={field.key}><Form.Item {...field} name={[field.name, "heading"]}><Input aria-label="Footer heading" /></Form.Item><Button onClick={() => remove(field.name)}>Remove</Button></Space>)}<Button onClick={() => add({ links: [] })}>Add footer column</Button></Card>}</Form.List><TranslationFields /><Button htmlType="submit" type="primary" loading={pending}>Save settings</Button>
  </Form>;
}

export function NavigationEditorForm({ initial, save }: { initial: { id?: string; slug: string; href: string; parentId: string | null; position: number; isVisible: boolean; version: string | null; translations: Array<{ locale: Locale; title: string }>; status: string }; save: Mutation }) {
  const [form] = Form.useForm(); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string>();
  return <Form form={form} layout="vertical" initialValues={{ ...initial, translations: Object.fromEntries(initial.translations.map((item) => [item.locale, item])) }} onFinish={(values) => startTransition(async () => { try { setError(undefined); await save({ ...initial, ...values, parentId: values.parentId || null, translations: SUPPORTED_LOCALES.flatMap((locale) => values.translations?.[locale]?.title ? [{ locale, title: values.translations[locale].title }] : []) }); } catch { setError("Could not save this navigation item."); } })}><Form.Item name="slug" label="Slug" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="href" label="Link"><Input /></Form.Item><Form.Item name="parentId" label="Parent menu ID"><Input /></Form.Item><Form.Item name="position" label="Position"><Input type="number" /></Form.Item>{error ? <p role="alert">{error}</p> : null}<Tabs items={SUPPORTED_LOCALES.map((locale) => ({ key: locale, label: locale, children: <Form.Item name={["translations", locale, "title"]} label="Label" rules={[{ required: locale === "en" }]}><Input /></Form.Item> }))} /><Button htmlType="submit" loading={pending}>Save menu item</Button></Form>;
}

export function PageEditorForm({ initial, save, publish, archive }: { initial: { id: string; slug: string; version: string; translations: Translation[] }; save: Mutation; publish: Mutation; archive: Mutation }) {
  const [form] = Form.useForm(); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string>();
  const submit = (kind: "save" | "publish" | "archive") => startTransition(async () => { try { setError(undefined); const values = await form.validateFields(); const data = { ...initial, slug: values.slug, translations: toTranslations(values.translations ?? {}) }; if (kind === "save") await save(data); else await (kind === "publish" ? publish : archive)({ pageId: initial.id, version: initial.version, status: kind === "publish" ? "PUBLISHED" : "ARCHIVED" }); } catch { setError("Could not update this page. Reload if another editor has changed it."); } });
  return <Form form={form} layout="vertical" initialValues={{ slug: initial.slug, translations: Object.fromEntries(initial.translations.map((item) => [item.locale, item])) }}><Form.Item name="slug" label="Slug" rules={[{ required: true }]}><Input /></Form.Item>{error ? <p role="alert">{error}</p> : null}<TranslationFields /><Space><Button type="primary" onClick={() => submit("save")} loading={pending}>Save draft</Button><Button onClick={() => submit("publish")} loading={pending}>Publish</Button><Button danger onClick={() => submit("archive")} loading={pending}>Archive</Button></Space></Form>;
}

export function PageSectionForm({ initial, save }: { initial: { id?: string; pageId: string; version: string | null; position: number; type: string; config: Record<string, unknown>; isEnabled: boolean; translations: Translation[] }; save: Mutation }) {
  const [form] = Form.useForm(); const [pending, startTransition] = useTransition(); const [kind, setKind] = useState(initial.type); const [error, setError] = useState<string>();
  const submit = (values: Record<string, unknown>) => startTransition(async () => { try { setError(undefined); const config = kind === "news" ? { count: Number(values.newsCount ?? 3) } : kind === "cta" ? { primaryCta: { label: String(values.ctaLabel ?? ""), href: String(values.ctaHref ?? "") } } : ["hero", "about", "quality"].includes(kind) && values.imageId ? { imageId: values.imageId } : {}; await save({ ...initial, type: kind, isEnabled: Boolean(values.isEnabled), config, translations: toTranslations(values.translations as Record<string, { title?: string; body?: string }>) }); } catch { setError("Could not save this section. Check the required fields."); } });
  return <Form form={form} layout="vertical" initialValues={{ ...initial, translations: Object.fromEntries(initial.translations.map((item) => [item.locale, item])), newsCount: initial.config.count ?? 3, imageId: initial.config.imageId, ctaLabel: (initial.config.primaryCta as { label?: string } | undefined)?.label, ctaHref: (initial.config.primaryCta as { href?: string } | undefined)?.href }} onFinish={submit}><Form.Item label="Section type"><Select value={kind} onChange={setKind} options={["hero", "services", "about", "capabilities", "quality", "product-categories", "global-reach", "stats", "news", "cta"].map((value) => ({ value }))} /></Form.Item>{["hero", "about", "quality"].includes(kind) ? <Form.Item name="imageId" label="Media ID"><Input /></Form.Item> : null}{kind === "news" ? <Form.Item name="newsCount" label="Article count"><Input type="number" /></Form.Item> : null}{kind === "cta" ? <><Form.Item name="ctaLabel" label="CTA label" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="ctaHref" label="CTA link" rules={[{ required: true }]}><Input /></Form.Item></> : null}<Form.Item name="isEnabled" valuePropName="checked" label="Enabled"><Switch /></Form.Item>{error ? <p role="alert">{error}</p> : null}<TranslationFields /><Button htmlType="submit" loading={pending}>Save section</Button></Form>;
}

export function MediaMetadataForm({ initial, save, archive, publish, allowArchive }: { initial: { id: string; version: string; translations: Translation[] }; save: Mutation; archive: Mutation; publish: Mutation; allowArchive: boolean }) {
  const [form] = Form.useForm(); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string>();
  return <Form form={form} initialValues={{ translations: Object.fromEntries(initial.translations.map((item) => [item.locale, item])) }} onFinish={(values) => startTransition(async () => { try { setError(undefined); await save({ ...initial, translations: toTranslations(values.translations ?? {}) }); } catch { setError("Could not save media metadata."); } })}>{error ? <p role="alert">{error}</p> : null}<TranslationFields media /><Space><Button htmlType="submit" loading={pending}>Save metadata</Button><Button onClick={() => startTransition(async () => publish({ mediaAssetId: initial.id, version: initial.version }))}>Publish media</Button>{allowArchive ? <Button danger onClick={() => startTransition(async () => archive({ mediaAssetId: initial.id }))}>Archive safely</Button> : null}</Space></Form>;
}
