version = 5.7.0
archive_dir = /etc/letsencrypt/archive/yueshou-peptide.com
cert = /etc/letsencrypt/live/yueshou-peptide.com/cert.pem
privkey = /etc/letsencrypt/live/yueshou-peptide.com/privkey.pem
chain = /etc/letsencrypt/live/yueshou-peptide.com/chain.pem
fullchain = /etc/letsencrypt/live/yueshou-peptide.com/fullchain.pem
[renewalparams]
account = 3b8313cc0c121a3946ca35e65dacea47
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
www.yueshou-peptide.com = /var/www/certbot
yueshou-peptide.com = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-08-13T08:45:04
