"use server";

import { revalidatePath } from "next/cache";
import { createProductAdminService } from "@/features/admin/products";
import { prismaProductAdminRepository, serializableRetry } from "@/features/admin/domain-repository";
import { invalidatePublishedCollection, invalidatePublishedEntity } from "@/features/publishing/cache";
import { requireRole, requireUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db/prisma";
import { SUPPORTED_LOCALES } from "@/lib/i18n/config";
import { z } from "zod";

const data = (input: unknown) => input instanceof FormData ? JSON.parse(String(input.get("payload") ?? "{}")) as object : input as object;
const service = () => createProductAdminService({ repository: prismaProductAdminRepository, invalidate: (type, slug) => invalidatePublishedEntity(type, slug, SUPPORTED_LOCALES) });
export async function saveProductAction(input: unknown) { const actor = await requireUser(); const payload = data(input) as { id?: string }; const before = payload.id ? await prisma.product.findUnique({ where: { id: payload.id }, select: { slug: true, status: true } }) : null; const result = await service().save({ ...(payload as object), status: "PUBLISHED", scheduledAt: null, actor }); const after = await prisma.product.findUniqueOrThrow({ where: { id: result.id }, select: { slug: true, status: true, updatedAt: true } }); if (before?.status === "PUBLISHED") invalidatePublishedEntity("product", before.slug, SUPPORTED_LOCALES); invalidatePublishedEntity("product", after.slug, SUPPORTED_LOCALES); invalidatePublishedCollection("product", SUPPORTED_LOCALES); revalidatePath("/admin/products"); return { ...result, status: after.status, version: after.updatedAt.toISOString() }; }
export async function deleteProductAction(formData: FormData) { const actor = await requireUser(); const payload = z.object({ id: z.string().min(1), version: z.string().datetime() }).parse({ id: formData.get("id"), version: formData.get("version") }); const product = await prisma.product.findFirst({ where: { id: payload.id, updatedAt: new Date(payload.version), deletedAt: null }, select: { slug: true } }); if (!product) throw new Error("产品已被其他管理员修改，请刷新后重试"); await prisma.$transaction(async (tx) => { await tx.product.update({ where: { id: payload.id }, data: { status: "ARCHIVED", deletedAt: new Date() } }); await tx.auditLog.create({ data: { actorId: actor.id, action: "PRODUCT_DELETED", entityType: "Product", entityId: payload.id } }); }); invalidatePublishedEntity("product", product.slug, SUPPORTED_LOCALES); invalidatePublishedCollection("product", SUPPORTED_LOCALES); revalidatePath("/admin/products"); }
const categoryPayload = z.object({ id: z.string().min(1).optional(), version: z.string().datetime().optional(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), title: z.string().trim().min(1).max(160), body: z.string().trim().max(4_000), status: z.enum(["DRAFT", "PUBLISHED"]).default("DRAFT") }).superRefine((value, context) => { if (value.id && !value.version) context.addIssue({ code: "custom", message: "version is required when editing a category" }); if (!value.id && value.version) context.addIssue({ code: "custom", message: "version is only valid when editing a category" }); });
export async function archiveProductCategoryAction(input: unknown) { const actor = await requireUser(); const payload = z.object({ categoryId: z.string().min(1), version: z.string().datetime() }).parse(data(input)); await service().archiveCategory({ categoryId: payload.categoryId, version: payload.version, actor }); invalidatePublishedCollection("product", SUPPORTED_LOCALES); revalidatePath("/admin/products"); }
export async function saveProductCategoryAction(input: unknown) { const actor = await requireRole("ADMIN"); const payload = categoryPayload.parse(data(input)); await serializableRetry(() => prisma.$transaction(async (tx) => { const previous = payload.id ? await tx.productCategory.findFirst({ where: { id: payload.id, updatedAt: new Date(payload.version!), deletedAt: null } }) : null; if (payload.id && !previous) throw new Error("Category changed by another administrator; reload and try again"); const category = previous ? await tx.productCategory.update({ where: { id: previous.id }, data: { slug: payload.slug, status: payload.status, publishedAt: payload.status === "PUBLISHED" ? previous.publishedAt ?? new Date() : previous.publishedAt } }) : await tx.productCategory.create({ data: { slug: payload.slug, status: payload.status, publishedAt: payload.status === "PUBLISHED" ? new Date() : null } }); await tx.productCategoryTranslation.upsert({ where: { productCategoryId_locale: { productCategoryId: category.id, locale: "en" } }, update: { title: payload.title, body: payload.body }, create: { productCategoryId: category.id, locale: "en", title: payload.title, body: payload.body } }); await tx.auditLog.create({ data: { actorId: actor.id, action: "PRODUCT_CATEGORY_SAVED", entityType: "ProductCategory", entityId: category.id, metadata: { status: payload.status } } }); }, { isolationLevel: "Serializable" })); invalidatePublishedCollection("product", SUPPORTED_LOCALES); revalidatePath("/admin/products"); }
