import type { Prisma } from "@prisma/client";
import { AdminPageTitle, Button, Card, Input, Space } from "@/components/admin/antd-server-bridge";
import { ManagementTable } from "@/components/admin/management-table";
import { requireUser } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db/prisma";
import { publicMediaUrl } from "@/features/media/public-url";
import { deleteProductAction } from "./actions";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: "DRAFT" | "PUBLISHED" | "ARCHIVED" }> }) { await requireUser(); const filters = await searchParams; const q = filters.q?.trim().slice(0, 100); const status = ["DRAFT", "PUBLISHED", "ARCHIVED"].includes(filters.status ?? "") ? filters.status : undefined; const where: Prisma.ProductWhereInput = { deletedAt: null, ...(status ? { status } : {}), ...(q ? { OR: [{ slug: { contains: q, mode: "insensitive" } }, { translations: { some: { title: { contains: q, mode: "insensitive" } } } }] } : {}) }; const products = await prisma.product.findMany({ where, include: { translations: { where: { locale: "en" }, take: 1 }, category: { include: { translations: { where: { locale: "en" }, take: 1 } } }, media: true }, orderBy: [{ updatedAt: "desc" }, { id: "asc" }] }); const rows = products.map((item) => { const coverId = item.specifications && typeof item.specifications === "object" && !Array.isArray(item.specifications) && "coverMediaId" in item.specifications ? (item.specifications as { coverMediaId?: unknown }).coverMediaId : undefined; const cover = typeof coverId === "string" ? item.media.find((media) => media.id === coverId) ?? item.media[0] : item.media[0]; return { id: item.id, title: item.translations[0]?.title ?? item.slug, imageUrl: cover ? publicMediaUrl(cover.id) : "/og.png", category: item.category.translations[0]?.title ?? item.category.slug, status: item.status, updatedAt: item.updatedAt.toLocaleString("zh-CN"), version: item.updatedAt.toISOString(), editHref: `/admin/products/${item.id}` }; }); return <main><Space style={{ width: "100%", justifyContent: "space-between" }}><AdminPageTitle level={1}>产品管理</AdminPageTitle><Button type="primary" href="/admin/products/new">新建产品</Button></Space><Card><form><Space wrap><Input name="q" defaultValue={q} placeholder="搜索产品" /><select name="status" defaultValue={status ?? ""}><option value="">全部状态</option><option value="PUBLISHED">已发布</option><option value="DRAFT">草稿</option></select><Button htmlType="submit">筛选</Button></Space></form><ManagementTable rows={rows} deleteAction={deleteProductAction} /></Card></main>; }
